services:
  EkbTramBotApp:
    container_name: EkbTramBotApp
    image: library/node:18-alpine
    user: "node"
    working_dir: /opt/project
    volumes:
      - ./:/opt/project
    command: sh -c "npm ci --omit=dev && npm run build && npm start"
