version: "3.1"
services:
  EkbTramBotApp:
    container_name: EkbTramBotApp
    image: library/node:lts-alpine3.18
    user: "node"
    working_dir: /opt/project
    volumes:
      - ./:/opt/project
    command: sh -c "npm install && npm run build && npm start"
