version: "3.1"
services:
  EkbTramBotApp:
    container_name: EkbTramBotApp
    image: library/node:14.15.4-alpine
    user: "node"
    working_dir: /opt/project
    volumes:
      - ./:/opt/project
    command: sh -c "npm install && node index.js"
